FROM iseletkov/scipy
RUN /usr/local/bin/pip install -U joblib --extra-index-url https://www.piwheels.org/simple
RUN /usr/local/bin/pip install -U scikit-learn --extra-index-url https://www.piwheels.org/simple

